In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("/content/u1.base", sep = "\t", engine = "python", header = None)

def funcion_convertidora(data):
  data = data.rename(columns = {0: "usuario", 1: "pelicula", 2: "valoracion", 3: "timesteps"})
  data = data.drop(labels = "timesteps", axis = 1)
  i = 1
  lista_usuario = []
  lista_total = []
  total_peliculas = int(data["pelicula"].max())
  total_usuarios = int(data["usuario"].max())
  j = 1
  z = 1
  contenedor = []
  while z <= total_peliculas:
    contenedor.append(z)
    z = z + 1
  usuarios = np.array([contenedor])
  j = 1
  while j <= total_usuarios:
    data_filtrado = data[data["usuario"] == j]
    while i <= total_peliculas:
      if i <= len(data_filtrado):
        a = i in data_filtrado.pelicula.values
        if a == True:
          lista_usuario.append(int(data_filtrado.iloc[i-1, 2]))
          i = i + 1
        if a == False:
          lista_usuario.append(0)
          i = i + 1
      else:
        lista_usuario.append(0)
        i = i + 1
    usuarios = np.insert(usuarios, usuarios.shape[0], [lista_usuario], axis = 0)
    j = j + 1
 # print(usuarios)

  usuarios2 = np.delete(usuarios, (0), axis = 0)
  #print("#########################")
  return (usuarios2)



  







In [3]:
print(funcion_convertidora(data))
beta = funcion_convertidora(data)

[[5 3 4 ... 0 0 0]
 [5 3 4 ... 0 0 0]
 [5 3 4 ... 0 0 0]
 ...
 [5 3 4 ... 0 0 0]
 [5 3 4 ... 0 0 0]
 [5 3 4 ... 0 0 0]]
